addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.3.0")
// addSbtPlugin("com.github.cb372"          % "sbt-explicit-dependencies" % "0.2.11")
// addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"              % "0.1.10")
// addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.9.25")
addSbtPlugin("ch.epfl.lamp" % "sbt-dotty" % "0.5.1")
